### ISSUE TITLE
Jakieś wyjasnienia zmiennych

### ISSUE THREAD

**Issue by Czester0** [tpay-com/tpay-openapi-php#1]
Ogólnie z prostych rzeczy jest zrobiony taki kombajn że szkoda gadać. Doszukać się jakiegokolwiek rozwiązania na stronę z dokumentacji Tpay to porażka. Ktoś powinien siąść i przeczytać to jeszcze raz. Poprawić linki do 404 oraz zdecydować się czy wersja angielska jest wzorem czy wersja polska bo to są dwie rózne rzeczy. Natomiast co do sedna sprawy - chciałbym aby ktoś wytłumaczył co to są za zmienne i skąd je pobrać. 
MERCHANT_CLIENT_ID
MERCHANT_CLIETN_SECRET
MERCHANT_CONFORMATION_CODE
MERCHANT_RSA_KEY
nigdzie niestety te zmienne nie występują w nomenklaturze helpu

**Comment by piotrjozwiak** [comment]
@Czester0 
W zależności od integracji, potrzebne są tylko niektóre z wskazanych wartości:
MERCHANT_CLIENT_ID i MERCHANT_CLIETN_SECRET to clientId i secret oAuth 2, które są podane w [Panelu Odbiorcy Płatności](https://panel.tpay.com/), w zakładce Integracja -> API w sekcji "Klucze do nowego Open Api". Te wartości są wymagane.
Jeśli nie ma Pan dostępu do tej zakładki, prosimy o kontakt z BOK Tpay.

Natomiast MERCHANT_CONFORMATION_CODE to kod zabezpieczający sumę kontrolną, sprawdzaną przy odbieraniu asynchronicznych powiadomień o płatnościach. Kod znajduje się w [Panelu Odbiorcy Płatności](https://panel.tpay.com/), w zakładce Ustawienia -> Powiadomienia. Zamiast odbierać powiadomienia, można też odpytywać serwer Tpay o status płatności meteodą [GET /transactions/{transactionId}
](https://openapi.tpay.com/#/transactions/get_transactions__transactionId_)

MERCHANT_RSA_KEY jest wymagany tylko przy integracji płatności kartowych on-site, gdzie szyfrowanie danych karty następuje po stronie merchant'a. Więcej informacji [support.tpay.com/pl/developer/openapi/platnosci-karta-na-stronie-sklepu](https://support.tpay.com/pl/developer/openapi/platnosci-karta-na-stronie-sklepu)

Szczegółowe artykuły wyjaśniające integrację Tpay, z wykorzystaniem biblioteki znajdują się pod adresem [https://support.tpay.com/pl/developer/openapi](https://support.tpay.com/pl/developer/openapi)

Wszystkie dane dostępowe należy przechowywać we własnym zakresie np. w pliku .env projektu. W bibliotece folder Examples zawiera jedynie proste przykłady wykorzystania większości metod Tpay, gdzie dla ułatwienia pracy mniej doświadczonym programistom dane dostępowe zostały przypisane do stałych w [ExamplesConfig](https://github.com/tpay-com/tpay-openapi-php/blob/801f42ac626d88a1f840dd6daf01b469e2b38ade/Examples/ExamplesConfig.php#L6).

Prosimy o wskazanie miejsc, gdzie napotkał Pan linki prowadzące do stron zwracających 404.
