### ISSUE TITLE
Brakuje statusu FALSE w odbieranej notyfikacji?

### ISSUE THREAD

**Issue by scardinius** [tpay-com/tpay-openapi-php#4]
Zrobiłem test opłacając transakcję częściowo. Dzięki temu udało mi się wywołać sytuację przekierowania na stronę błędu (definiowaną przez *callbacks.payerUrls.error*). Natomiast obsługując notyfikację wg instrukcji https://support.tpay.com/pl/developer/openapi/odbieranie-powiadomienia-o-wplacie czyli za pomocą biblioteki OpenAPI w takiej sytuacji nie otrzymuję notyfikacji. W dokumentacji jest zdanie *After each successful transaction or manual chargeback of **full amount** made in Merchant Panel, the following parameters will be sent to your endpoint URL*.

Gdy ręcznie wymusiłem wysłanie notyfikacji to otrzymałem wyjątek:

```
  "message" => """
    Array\n
    (\n
        [0] => Value of field tr_status is invalid. Should be one of Array\n
    (\n
        [0] => TRUE\n
        [1] => PAID\n
        [2] => CHARGEBACK\n
    )\n
    \n
    )\n
    """
```

W zmiennej $_POST są wartości :

```
    [tr_status] => FALSE
    [tr_error] => surcharge
```

Skoro użytkownik może być przekierowany na stronę błędu to dlaczego nie ma analogicznej notyfikacji?

Wg dokumentacji wychodzi na to, że nie otrzymam notyfikacji o błędnej transakcji. W takim razie na jakiej podstawie mam zmienić status transakcji w moim systemie? Mam po jakimś czasie (jakim?) odpytać o konkretną transakcję? https://openapi.tpay.com/#/transactions/get_transactions__transactionId_ 

Proszę o wyjaśnienie.

EDIT:
Znalazłem sposób testowania nieudanej płatności poprzez panel *Integracja > Testowanie powiadomień*. Tutaj ustawiając parametr *status transakcji* na `incorrect` w otrzymanej notyfikacji mam taką tablicę $_POST:

```
$notification->getNotificationAssociative() = Array
(
    [id] => 11111
    [tr_id] => TR-1111-22222
    [tr_date] => 2022-01-13 12:43:46
    [tr_crc] => id-123
    [tr_amount] => 11
    [tr_paid] => 11
    [tr_desc] => test z panelu na statusie incorrect
    [tr_status] => FALSE
    [tr_error] => none
    [tr_email] => test@example.com
    [md5sum] => 2fb4e501aa2ca439a6a2fee30a308f46
)
```

Jednak jest status `FALSE`! Co ciekawe, taka notyfikacja nie ma ustawionego parametru *test_mode*.

**Comment by BanczerowskiM** [comment]
Gdy płatnik wpłaci zbyt małą kwotę za całą transakcję, nasz system nie wyśle żadnego powiadomienia do sprzedawcy oraz automatycznie wygeneruje i wyśle płatnikowi link umożliwiający dopłatę brakującej kwoty. W takim przypadku można poczekać, aż płatnik dopłaci brakujące środki lub samodzielnie przyjąć/zwrócić transakcję w Panelu Odbiorcy Płatności. Jeśli płatnik wykona dopłatę, w zależności od sumy wpłaconych środków następuje ponowna weryfikacja. Jeśli kwota zostanie uzupełniona o brakujące środki, system wyśle powiadomienie o poprawnej płatności.
Jeśli transakcja nie przyjmie żadnego ze statusów, nie zostanie do niej wysłana notyfikacja: TRUE\PAID\CHARGEBACK

Mimo iż nasz system jest w stanie wysłać powiadomienie dla transakcji, która przyjmuje status transakcji FALSE (np. poprzez wykonanie testu w zakładce Integracja > Testowanie powiadomień).
To dla transakcji wykonywanych przez naszą bibliotekę nie zostało ono zaimplementowane. Takie powiadomienie zostało wysłane, ponieważ konto ma włączone automatyczne akceptowanie niedopłat (max. 2 zł poniżej kwoty transakcji) lub automatycznie akceptowanie nadpłat. W Panelu Odbiorcy Płatności funkcję te można wyłączyć, wchodząc w zakładkę Transakcje -> Ustawienia.

W przyszłości zamierzamy zlikwidować mechanizm umożliwiający płatnikami wykonania nadpłaty i niedopłaty, dlatego nie planujemy dodawać tej opcji w naszej bibliotece.
