### ISSUE TITLE
This language is not supported: pl

### ISSUE THREAD

**Issue by kgzhy** [tpay-com/tpay-openapi-php#47]
`<?php exit; ?> 

===========================
Outgoing request
===========================
2023-09-28 23:10:08
ip: 127.0.0.1
URL: https://openapi.sandbox.tpay.com/oauth/auth 
 Method: POST 
 Fields: {"client_id":"01HBEPBS7WV6NMYH4HSXG996AE-01HBEPE3Z8KJKRM6REYD5QW6HB","client_secret":"XXX","scope":"read"} 
 Headers: ["Content-Type: application\/json"]

===========================
Request response
===========================
2023-09-28 23:10:09
ip: 127.0.0.1
Fields: {"issued_at":1695942609,"scope":"read","token_type":"Bearer","expires_in":7200,"client_id":"01HBEPBS7WV6NMYH4HSXG996AE-01HBEPE3Z8KJKRM6REYD5QW6HB","access_token":"d0cb8cf77b3ad57166c5cb6d5934f9f8fe125feb"} 
 HTTP code: 200

===========================
Outgoing request
===========================
2023-09-28 23:10:09
ip: 127.0.0.1
URL: https://openapi.sandbox.tpay.com/transactions/bank-groups?onlyOnline=true 
 Method: GET 
 Fields: [] 
 Headers: ["Authorization: Bearer d0cb8cf77b3ad57166c5cb6d5934f9f8fe125feb"]

===========================
Request response
===========================
2023-09-28 23:10:09
ip: 127.0.0.1
Fields: {"result":"success","requestId":"7ef3b585429d8cddf803","groups":{"103":{"id":"103","name":"Karta p\u0142atnicza","img":"https:\/\/secure.tpay.com\/_\/g\/103.png","availablePaymentChannels":["53"],"mainChannel":"53"},"113":{"id":"113","name":"Alior Bank SA","img":"https:\/\/secure.tpay.com\/_\/g\/113.png","availablePaymentChannels":["9"],"mainChannel":"9"},"102":{"id":"102","name":"Bank Pekao SA","img":"https:\/\/secure.tpay.com\/_\/g\/102.png","availablePaymentChannels":["4","47","55"],"mainChannel":"4"},"108":{"id":"108","name":"PKO Bank Polski","img":"https:\/\/secure.tpay.com\/_\/g\/108.png","availablePaymentChannels":["21"],"mainChannel":"21"},"110":{"id":"110","name":"Inteligo","img":"https:\/\/secure.tpay.com\/_\/g\/110.png","availablePaymentChannels":["14"],"mainChannel":"14"},"150":{"id":"150","name":"BLIK","img":"https:\/\/secure.tpay.com\/_\/g\/150.png","availablePaymentChannels":["64"],"mainChannel":"64"},"160":{"id":"160","name":"mBank","img":"https:\/\/secure.tpay.com\/_\/g\/160.png","availablePaymentChannels":["18"],"mainChannel":"18"},"111":{"id":"111","name":"ING Bank \u015al\u0105ski SA","img":"https:\/\/secure.tpay.com\/_\/g\/111.png","availablePaymentChannels":["13"],"mainChannel":"13"},"114":{"id":"114","name":"Bank Millennium SA","img":"https:\/\/secure.tpay.com\/_\/g\/114.png","availablePaymentChannels":["2","48"],"mainChannel":"2"},"115":{"id":"115","name":"Santander Bank Polska SA","img":"https:\/\/secure.tpay.com\/_\/g\/115.png","availablePaymentChannels":["6"],"mainChannel":"6"},"132":{"id":"132","name":"Citibank Handlowy SA","img":"https:\/\/secure.tpay.com\/_\/g\/132.png","availablePaymentChannels":["7"],"mainChannel":"7"},"116":{"id":"116","name":"Credit Agricole Polska SA","img":"https:\/\/secure.tpay.com\/_\/g\/116.png","availablePaymentChannels":["17"],"mainChannel":"17"},"119":{"id":"119","name":"Velo Bank","img":"https:\/\/secure.tpay.com\/_\/g\/119.png","availablePaymentChannels":["12"],"mainChannel":"12"},"124":{"id":"124","name":"Bank Pocztowy SA","img":"https:\/\/secure.tpay.com\/_\/g\/124.png","availablePaymentChannels":["5"],"mainChannel":"5"},"135":{"id":"135","name":"Banki Sp\u00f3\u0142dzielcze","img":"https:\/\/secure.tpay.com\/_\/g\/135.png","availablePaymentChannels":["42","63"],"mainChannel":"63"},"133":{"id":"133","name":"BNP Paribas Bank Polska SA","img":"https:\/\/secure.tpay.com\/_\/g\/133.png","availablePaymentChannels":["1"],"mainChannel":"1"},"159":{"id":"159","name":"Neo Bank","img":"https:\/\/secure.tpay.com\/_\/g\/159.png","availablePaymentChannels":["24"],"mainChannel":"24"},"130":{"id":"130","name":"Nest Bank","img":"https:\/\/secure.tpay.com\/_\/g\/130.png","availablePaymentChannels":["26"],"mainChannel":"26"},"145":{"id":"145","name":"Plus Bank SA","img":"https:\/\/secure.tpay.com\/_\/g\/145.png","availablePaymentChannels":["15"],"mainChannel":"15"},"166":{"id":"166","name":"Google Pay","img":"https:\/\/secure.tpay.com\/_\/g\/166.png","availablePaymentChannels":["68"],"mainChannel":"68"},"170":{"id":"170","name":"Apple Pay","img":"https:\/\/secure.tpay.com\/_\/g\/170.png","availablePaymentChannels":["75"],"mainChannel":"75"},"171":{"id":"171","name":"Visa Mobile","img":"https:\/\/secure.tpay.com\/_\/g\/171.png","availablePaymentChannels":["79"],"mainChannel":"79"}}} 
 HTTP code: 200

===========================
TpayException
===========================
2023-09-28 23:10:09
ip: 127.0.0.1
This language is not supported: pl in file D:\xampp\htdocs\j4\plugins\vmpayment\ignisdev_tpay\Tpay\OpenApi\Locale\Lang.php line: 23 

#0 D:\xampp\htdocs\j4\plugins\vmpayment\ignisdev_tpay\Tpay\OpenApi\Utilities\Util.php(105): Tpay\OpenApi\Locale\Lang::setLang('pl')
#1 D:\xampp\htdocs\j4\plugins\vmpayment\ignisdev_tpay\Tpay\OpenApi\Forms\PaymentForms.php(15): Tpay\OpenApi\Utilities\Util::setLanguage('pl')
#2 D:\xampp\htdocs\j4\plugins\vmpayment\ignisdev_tpay\ignisdev_tpay.php(258): Tpay\OpenApi\Forms\PaymentForms->__construct('pl')
[...]
`

**Comment by kwojc** [comment]
@kgzhy Sorry for lack of response. This issue was fixed 9 month ago: https://github.com/tpay-com/tpay-openapi-php/commit/7cc4a1039539e5471f1b2559aa3cea0d7a9c49b4
