### ISSUE TITLE
W jaki sposób metoda sale różni się od securesale w przypadku OpenAPI? [Płatności kartami]

### ISSUE THREAD

**Issue by PSzczepanski996** [tpay-com/tpay-openapi-php#5]
Hej,
Pisałem do was na pocztę ale może szybciej otrzymam tutaj odpowiedź.
Zintegrowałem system płatności i chciałem go przetestować (a stricte przetestować płatności kartami kredytowymi) za pomocą kluczy demo, co wielokrotnie nie przechodziło.
Za to klucze z konta "oficjalnego", produkcyjnego, potwierdzonego przez Elavon, przechodzą bez problemu, ba, ściągają mi pieniądze z konta revolut.
Zgaduję że klient z którym współpracuję nie odblokował metody `securesale`, która w dokumentacji OpenAPI nie jest opisana w żaden możliwy sposób.

Uznałem, że może nie przekazuję parametru `sign`, ale i przy tworzeniu transakcji, i przy płaceniu kartą, API zwraca mi odpowiedź że takie pole jest zbędne i wywala wyjątek. W panelu istnieje klucz API i kod weryfikacyjny do płatności kartą - a jak widzę, cały panel jest zrobiony w stylu "nowym" tak jakby był dedykowany "nowemu API" - więc jak mam te zmienne przekazać?

W koncie `1010/demo` nie ma też możliwości wyłączenia trybu testowego. Uznałem że może muszę klucz API do płatności kartami przekazać w headersach, ale klucz headerów `Authorization` z wartością `Bearer <tu_klucz_api>` nie rozwiązuje mojego problemu.

Totalnie się już gubię, sprawdziłem wielokrotnie klucze którymi łączę się w momencie tworzenia transakcji, sprawdziłem dane które wysyłam, wysyłałem wam requestId, i nie widzę innego sposobu niż po prostu testowanie kodu za pomocą kluczy produkcyjnych. Czy OpenAPI nie działa, czy jest źle udokumentowane? Czy w takim razie opcja SecureSale coś psuje w przypadku testowania płatności kartami i powinna zostać wyłączona? Czemu nie ma ani jednej wzmianki co ona powoduje i co trzeba zmienić w wysyłanych requestach?

**Comment by BanczerowskiM** [comment]
System Tpay umożliwią integrację API na dwa sposoby, za pomocą biblioteki https://github.com/tpay-com/tpay-php, do której należy dokumentacja https://docs.tpay.com/, dla niej dane takie jak kod bezpieczeństwa znajdziemy w zakładce Ustawienia -> Powiadomienia oraz dane do API w zakładce Integracja -> API w sekcji "Klucze do starego Api".
Drugim sposobem jest integracja przez bibliotekę https://github.com/tpay-com/tpay-openapi-php, do której należy dokumentacja https://openapi.tpay.com/. Dane do integracji Open API znajdują się w zakładce Integracja -> API w sekcji "Klucze do nowego Open Api" i nie będą konieczne żadne dodatkowe dane.

Integrację różnią się od siebie, np. Open API nie ma podziału na różne metody płatności, wszystkie trafiają do jednej listy transakcji. Dlatego dla płatności kartowych nie wysyłamy parametru "sing", który był konieczny dla metody securesale (w tym API ta metoda nie występuje) ani również nie przekazujemy klucza API, kodu weryfikującego.

Aby zaimplementować płatności kartowe, należy utworzyć plik Config.php i umieścić tam niezbędne dane według przykładu tpay-openapi-php/Examples/ExamplesConfig.php. Zaszyfrowane dane karty przekazujemy funkcja makeCardPayment() w zmiennej $cardData.
